In [42]:
# Import Libraries
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report

In [9]:
# Load Training & Test Data
data_train = pd.read_csv(r"C:\Users\User\Desktop\Mark-D1 (H.A.R.)\train.csv")
data_test = pd.read_csv(r"C:\Users\User\Desktop\Mark-D1 (H.A.R.)\test.csv")
print("Training data size: ", data_train.shape)
print("Test data size: ", data_test.shape)

Training data size:  (7352, 563)
Test data size:  (2947, 563)


In [13]:
data_train[:5]

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  \
0           0.288585          -0.020294          -0.132905         -0.995279   
1           0.278419          -0.016411          -0.123520         -0.998245   
2           0.279653          -0.019467          -0.113462         -0.995380   
3           0.279174          -0.026201          -0.123283         -0.996091   
4           0.276629          -0.016570          -0.115362         -0.998139   

   tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  \
0         -0.983111         -0.913526         -0.995112         -0.983185   
1         -0.975300         -0.960322         -0.998807         -0.974914   
2         -0.967187         -0.978944         -0.996520         -0.963668   
3         -0.983403         -0.990675         -0.997099         -0.982750   
4         -0.980817         -0.990482         -0.998321         -0.979672   

   tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  fBodyBodyGyroJerkMag-kurtosis()  \
0         -0.923527         -0.934724  ...                        -0.710304   
1         -0.957686         -0.943068  ...                        -0.861499   
2         -0.977469         -0.938692  ...                        -0.760104   
3         -0.989302         -0.938692  ...                        -0.482845   
4         -0.990441         -0.942469  ...                        -0.699205   

   angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
0                    -0.112754                              0.030400   
1                     0.053477                             -0.007435   
2                    -0.118559                              0.177899   
3                    -0.036788                             -0.012892   
4                     0.123320                              0.122542   

   angle(tBodyGyroMean,gravityMean)  angle(tBodyGyroJerkMean,gravityMean)  \
0                         -0.464761                             -0.018446   
1                         -0.732626                              0.703511   
2                          0.100699                              0.808529   
3                          0.640011                             -0.485366   
4                          0.693578                             -0.615971   

   angle(X,gravityMean)  angle(Y,gravityMean)  angle(Z,gravityMean)  subject  \
0             -0.841247              0.179941             -0.058627        1   
1             -0.844788              0.180289             -0.054317        1   
2             -0.848933              0.180637             -0.049118        1   
3             -0.848649              0.181935             -0.047663        1   
4             -0.847865              0.185151             -0.043892        1   

   Activity  
0  STANDING  
1  STANDING  
2  STANDING  
3  STANDING  
4  STANDING  

[5 rows x 563 columns]

In [11]:
# Class Distribution
data_distribution = pd.crosstab(index=data_train['Activity'], columns='Total_samples')
print("\nSamples per activity: \n\n", data_distribution)


Samples per activity: 

 col_0               Total_samples
Activity                         
LAYING                       1407
SITTING                      1286
STANDING                     1374
WALKING                      1226
WALKING_DOWNSTAIRS            986
WALKING_UPSTAIRS             1073


In [31]:
# Take out features for training and testing
train_data = data_train.iloc[:, 0:561]
test_data = data_test.iloc[:, 0:561]
train_label = data_train.iloc[:, 562:563] 
test_label = data_test.iloc[:, 562:563]
print("Training data size: ", train_data.shape)
print("Test data size: ", test_data.shape)
print("Training label size: ", train_label.shape)
print("Test label size: ", test_label.shape)

Training data size:  (7352, 561)
Test data size:  (2947, 561)
Training label size:  (7352, 1)
Test label size:  (2947, 1)


In [32]:
# Checking for any null value in training dataset
print("Is there any missing value:  ", train_data.isnull().values.any())

Is there any missing value:   False


In [35]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
LogReg = LogisticRegression()
LogReg.fit(train_data, train_label)

pred = LogReg.predict(test_data)
accuracy = LogReg.score(test_data, test_label)
print("\nTest Accuracy: ", accuracy*100)
print("\nConfusion Matrix: \n", confusion_matrix(test_label, pred))

C:\Users\User\anaconda3\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)



Test Accuracy:  95.79233118425518

Confusion Matrix: 
 [[537   0   0   0   0   0]
 [  0 430  58   0   0   3]
 [  0  16 516   0   0   0]
 [  0   0   0 492   3   1]
 [  0   0   0   4 403  13]
 [  0   0   0  24   2 445]]


C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [41]:
# Support Vector Machine
rbf = SVC(kernel='rbf', gamma=0.0009, C=100)
rbf.fit(train_data, train_label)
pred = rbf.predict(test_data)
print("Test Accuracy:, ", rbf.score(test_data, test_label)*100)
print("\nConfusion Matrix:\n", confusion_matrix(test_label, pred))

C:\Users\User\anaconda3\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Test Accuracy:,  96.16559212758737

Confusion Matrix:
 [[537   0   0   0   0   0]
 [  0 435  54   0   0   2]
 [  0  14 518   0   0   0]
 [  0   0   0 492   3   1]
 [  0   0   0   4 406  10]
 [  0   0   0  24   1 446]]
